// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

contract TokenGenerator {
    address public admin;
    
    // Mapping to track which voter IDs have been issued tokens
    mapping(string => bool) public voterIdUsed;
    mapping(bytes32 => bool) public tokenGenerated;
    
    event TokenGenerated(string indexed voterId, bytes32 tokenHash);
    
    modifier onlyAdmin() {
        require(msg.sender == admin, "Only admin can call this function");
        _;
    }
    
    constructor() {
        admin = msg.sender;
    }
    
    // Generate a token hash for a verified voter
    function generateToken(string memory _voterId, uint256 _randomSalt) 
        public 
        onlyAdmin 
        returns (bytes32) 
    {
        require(!voterIdUsed[_voterId], "Token already generated for this voter ID");
        
        // Create a unique token hash
        bytes32 tokenHash = keccak256(abi.encodePacked(_voterId, _randomSalt, block.timestamp));
        
        require(!tokenGenerated[tokenHash], "Token collision, try again");
        
        // Mark voter ID as used
        voterIdUsed[_voterId] = true;
        tokenGenerated[tokenHash] = true;
        
        emit TokenGenerated(_voterId, tokenHash);
        
        return tokenHash;
    }
    
    // Check if voter ID has already been issued a token
    function hasToken(string memory _voterId) public view returns (bool) {
        return voterIdUsed[_voterId];
    }
    
    // Verify a token was generated by this contract
    function verifyToken(bytes32 _tokenHash) public view returns (bool) {
        return tokenGenerated[_tokenHash];
    }
}